name: lintTestDeploy
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Lint project
              run: npm run lint
            - name: Run Tests
              run: npm run test
            - name: Build Project
              run: npm run build
            - name: Deploy Code
              run: echo "Deploying..."
               
